In [ ]:
import numpy as np

In [ ]:
swarm_input=6
emp_bee=onlooker=swarm_input//2

In [ ]:
def initial_sol(emp_bees, vari):
  sol=np.zeros(shape=(emp_bees, vari))
  for i in range(emp_bees):
    for j in range(vari):
      val=0+np.random.random()*(8-0)
      sol[i][j]=val
  return sol

In [ ]:
sol=initial_sol(emp_bee, 3)

In [ ]:
sol

array([[2.00364535, 4.40264985, 0.81363473],
       [7.04637895, 3.13208394, 6.97855228],
       [5.74339201, 6.30668275, 3.45464051]])

In [ ]:
def fitness(sol, emp_bee):
  obj_value=np.zeros(shape=(emp_bee))
  fit_value=np.zeros(shape=(emp_bee))
  for i in range(emp_bee):
    result=0
    for j in range(3):
      result=result+(sol[i][j])**2
    if result>=0:
      f=1/(1+result)
    else:
      f=1+np.abs(result)
    obj_value[i]=result
    fit_value[i]=f
  return obj_value, fit_value

In [ ]:
obj_value, fit_value=fitness(sol, emp_bee)

In [ ]:
obj_value

array([ 24.05992183, 108.16159799,  84.69534012])

In [ ]:
fit_value

array([0.03990435, 0.00916073, 0.01166925])

In [ ]:
trial=np.array([0, 0, 0])

In [ ]:
def emp_phase(sol, emp_bee, vari, fit_value, obj_val, trial):
  for i in range(emp_bee):
    print("Bee: ", i)
    r1=np.random.randint(0, vari-1)
    print("Variable Selected: ",r1)
    xnew=sol[i]
    print("Old Values:", xnew)
    r2=np.random.randint(0, emp_bee-1)
    
    if r2==i and r2==emp_bee-1:
      r2=0
    elif r2==i:
      r2+=1
    print("Partner sol: ", r2)
    new_val=sol[i][r1]+np.random.uniform(-1,1)*(sol[i][r1]-sol[r2][r1])
    if new_val < 0:
      new_val=0
    elif new_val>8:
      new_val=8
    print("Value to modify: ", new_val)
    xnew[r1]=new_val
    print("new values: ", xnew)
    new_f=xnew[0]**2+xnew[1]**2+xnew[2]**2
    new_fit=1/(1+new_f)
    print("new fitness: ", new_fit)
    print("old fitness: ",fit_value[i])
    if new_fit>fit_value[i]:
      print(xnew)
      sol[i]=xnew
      fit_value[i]=new_fit
      obj_value[i]=new_f
      trial[i]=0
    else:
      trial[i]=trial[i]+1
  return sol, trial, fit_value, obj_value


In [ ]:
sol, trial, fit_value, obj_value=emp_phase(sol, emp_bee, 3, fit_value, obj_value, trial )

Bee:  0
Variable Selected:  1
Old Values: [2.00364535 4.40264985 0.81363473]
Partner sol:  1
Value to modify:  4.7347214181451465
new values:  [2.00364535 4.73472142 0.81363473]
new fitness:  0.03559455698472503
old fitness:  0.03990435431461439
Bee:  1
Variable Selected:  1
Old Values: [7.04637895 3.13208394 6.97855228]
Partner sol:  0
Value to modify:  2.0382316132251743
new values:  [7.04637895 2.03823161 6.97855228]
new fitness:  0.009661272286083801
old fitness:  0.009160730682148396
[7.04637895 2.03823161 6.97855228]
Bee:  2
Variable Selected:  0
Old Values: [5.74339201 6.30668275 3.45464051]
Partner sol:  1
Value to modify:  5.213492721532091
new values:  [5.21349272 6.30668275 3.45464051]
new fitness:  0.012517321680341779
old fitness:  0.011669245942930135
[5.21349272 6.30668275 3.45464051]


In [ ]:
sol

array([[2.00364535, 4.73472142, 0.81363473],
       [7.04637895, 2.03823161, 6.97855228],
       [5.21349272, 6.30668275, 3.45464051]])

In [ ]:
trial

array([1, 0, 0])

In [ ]:
def onlooker_phase(sol, emp_bee, vari, fit_value, obj_value, trial):
  probability=np.zeros(shape=(emp_bee))
  max_fit=max(fit_value)
  for i in range(emp_bee):
    probability[i]=0.9*(fit_value[i]/max_fit)+0.1
  print("Probability Values: ", probability)
  for i in range(emp_bee):
    print("Onlooker Bee: ",i)
    p_sol=i
    r=np.random.random()
    print("random_number: ", r)
    while r>probability[p_sol]:
      p_sol=i+1
      if p_sol==emp_bee:
        p_sol=0
      r=np.random.random()
      print("random_number: ",r)
    print("Food Source: ", p_sol)
    r1=np.random.randint(0, vari-1)
    print("Variable Selected: ",r1)
    xnew=sol[p_sol]
    print("Old Values:", xnew)
    r2=np.random.randint(0, emp_bee-1)
    if p_sol==r2 and p_sol==emp_bee-1:
      r2=0
    elif r2==p_sol:
      r2+=1
    print("Partner sol: ", r2)
    new_val=sol[p_sol][r1]+np.random.uniform(-1,1)*(sol[p_sol][r1]-sol[r2][r1])
    if new_val < 0:
      new_val=0
    elif new_val>8:
      new_val=8
    print("Value to modify: ", new_val)
    xnew[r1]=new_val
    print("new values: ", xnew)
    new_f=(xnew[0]**2)+(xnew[1]**2)+(xnew[2]**2)
    new_fit=1/(1+new_f)
    print("new fitness: ", new_fit)
    print("old fitness: ",fit_value[p_sol])
    if new_fit>fit_value[p_sol]:
      print(xnew)
      sol[p_sol]=xnew
      fit_value[p_sol]=new_fit
      obj_value[p_sol]=new_fit
      trial[p_sol]=0
    else:
      trial[p_sol]=trial[p_sol]+1
  return sol, trial, fit_value, obj_value


In [ ]:
sol, trial, fit_value, obj_value= onlooker_phase(sol,emp_bee, 3, fit_value, obj_value, trial)

Probability Values:  [1.         0.31789966 0.38231479]
Onlooker Bee:  0
random_number:  0.9291546452867744
Food Source:  0
Variable Selected:  1
Old Values: [2.00364535 4.73472142 0.81363473]
Partner sol:  1
Value to modify:  2.263730067494433
new values:  [2.00364535 2.26373007 0.81363473]
new fitness:  0.09258342019257942
old fitness:  0.03990435431461439
[2.00364535 2.26373007 0.81363473]
Onlooker Bee:  1
random_number:  0.7930018281944705
random_number:  0.11887070759861396
Food Source:  2
Variable Selected:  0
Old Values: [5.21349272 6.30668275 3.45464051]
Partner sol:  1
Value to modify:  4.7193676776226905
new values:  [4.71936768 6.30668275 3.45464051]
new fitness:  0.013336672912135137
old fitness:  0.012517321680341779
[4.71936768 6.30668275 3.45464051]
Onlooker Bee:  2
random_number:  0.9899456541739051
random_number:  0.33915621988746614
Food Source:  0
Variable Selected:  1
Old Values: [2.00364535 2.26373007 0.81363473]
Partner sol:  1
Value to modify:  2.197024772399951


In [ ]:
trial

array([0, 0, 0])

In [ ]:
limit=1

In [ ]:
def scout_bee(vari, obj_value, fit_value):
  new_sol=np.zeros(shape=(vari))
  for i in range(vari):
    val=0+np.random.random()*(8-0)
    new_sol[i]=val
  obj_value[i]=new_sol[0]**2+new_sol[1]**2+new_sol[2]**2
  if obj_value[i]>=0:
    fit_value[i]=1/(1+obj_value[i])
  else:
    fit_value[i]=1+abs(obj_value[i])
  
  return new_sol, obj_value, fit_value

In [ ]:
for i in range(emp_bee):
  if trial[i]>limit:
    print(i, "food source exhausted")
    print("Old Value", sol[i])
    new_sol, obj_value, fit_value=scout_bee(3, obj_value, fit_value)
    print("New Value", new_sol)
    sol[i]=new_sol
    trial[i]=0
  

In [ ]:
trial

array([0, 0, 0])

In [ ]:
swarm_input=8
emp_bee=onlooker=swarm_input//2
sol=initial_sol(emp_bee, 3)
print("Initial Solutions: ", sol)
limit=2
obj_value, fit_value=fitness(sol, emp_bee)
print("Employee bee phase: ")
trial=np.zeros(shape=(emp_bee))
sol, trial, fit_value, obj_value=emp_phase(sol, emp_bee, 3, fit_value, obj_value, trial )
print("Solutions by Employee bee: ", sol)
for i in range(5):
  print("Onlooker bee phase: ")
  sol, trial, fit_value, obj_value= onlooker_phase(sol,emp_bee, 3, fit_value, obj_value, trial)
  print("Solutions by onlooker bee: ", sol)
  print("Fitness Values: ", fit_value)
  for i in range(emp_bee):
    if trial[i]>limit:
      
      print(i, "food source exhausted, Bee enters into scout phase.")
      print("Old Value", sol[i])
      
      new_sol, obj_value, fit_value=scout_bee(3, obj_value, fit_value)
      print("New Values from scout bee: ", new_sol)
      sol[i]=new_sol
      trial[i]=0

print("Best Fitness: ",max(fit_value))
print("Best Objective: ", min(obj_value))


Initial Solutions:  [[1.55292381 2.71078968 0.07396679]
 [6.58190196 2.23118521 7.36631275]
 [4.49920756 2.47202511 0.88436441]
 [3.8778487  0.3944846  5.41077315]]
Employee bee phase: 
Bee:  0
Variable Selected:  0
Old Values: [1.55292381 2.71078968 0.07396679]
Partner sol:  1
Value to modify:  0
new values:  [0.         2.71078968 0.07396679]
new fitness:  0.11970526050330675
old fitness:  0.0928899771373764
[0.         2.71078968 0.07396679]
Bee:  1
Variable Selected:  1
Old Values: [6.58190196 2.23118521 7.36631275]
Partner sol:  2
Value to modify:  2.3855661428624804
new values:  [6.58190196 2.38556614 7.36631275]
new fitness:  0.009590033477170743
old fitness:  0.00965603425592932
Bee:  2
Variable Selected:  0
Old Values: [4.49920756 2.47202511 0.88436441]
Partner sol:  0
Value to modify:  6.291384225426247
new values:  [6.29138423 2.47202511 0.88436441]
new fitness:  0.021063928937055804
old fitness:  0.03554180995527769
Bee:  3
Variable Selected:  0
Old Values: [3.8778487  0.39